# Generated by Django 3.2.3 on 2021-05-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='navbar',
            field=models.BooleanField(default=True),
        ),
    ]
