# Generated by Django 3.2.3 on 2021-05-29 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='post',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='website.post'),
        ),
    ]
