# Generated by Django 3.2.3 on 2021-06-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='navbar',
            field=models.BooleanField(default=False),
        ),
    ]
