# Generated by Django 3.2.3 on 2021-06-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
