# Generated by Django 3.2.3 on 2021-06-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_messages_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
